version: '3.8'

services:
  movies:
    build:
      context: ./movies
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/

  historial:
    build:
      context: ./historial
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  recomendador:
    build:
      context: ./recomendador
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - movies
      - historial

  randommovies:
    build:
      context: ./randommovies
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - movies

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
    depends_on:
      - randommovies

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:
